Title: Errors
Author: Jon Reades
Theme: casa notes
Palette: Purple
Size: Wide
---
Layout: Title
# Ooops, I did it Again...

---
> We all make mistakes, it's how we deal with them that matters. It's the same in Python: understanding and handling errors is the key to good code.

---
## Helpfully...

Python will always try to tell you what it **think** when wrong: "I didn't understand what you meant by this..." or "I'm sorry, I can't let you do that Dave..."

The challenges are:
1. That what Python thinks the problem is doesn't always line up with where the problem *actually* is. In cases of syntax, for instance, the problem *could* be an unclosed parenthesis **three lines earlier**!
2. Python tends to give you a *lot* of information about the error: this can be very helpful for programmers dealing with complex problems and **totally overwhelming** for beginners.

---
### Challenge 1

---
### Challenge 2

---
## Errors Have Types

> In the same way that variables have types, so do errors. These types give us insight into the issue, but they also allow us to distinguish between different types of errors.

![](mi_question_answer)  Why might the ability to distinguish between different types of errors be helpful?

---
### Trapping Errors

We might reasonably want to distinguish between errors that we could reasonably **expect** or that are **not serious**, from those that **we did not expect** or that **call the results of the programme into question**.

> So it makes sense to think: "Well, let's **try** this and see what happens. If we have a problem of *this* type then it's not serious and we should carry on. But if we have a problem *that* type then we need to stop what we're doing right away."

---
## Python's Approach

Python calls errors **exceptions**, so this leads to:
```
try:
  ... some code that might fail...
except <Named Error Type>:
  ... what do it if it fails for a specific reason...
except:
  ... what to do if it fails...
finally:
  ... always do this, even if it fails...
```
We can even *create* our own problems:
```
raise Exception("Sorry, I can't let you do that, Dave.")
```

---
### For Example

If `x=10` and `y=0` then: 
```
print(x/y)
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> ZeroDivisionError: division by zero
```

But if you 'trap' the error using `except` then: 
```
try:
  print(x/y)
except ZeroDivisionError:
  print("You can't divide by zero!")
finally: 
  print("Division is fun!")

> You can't divide by zero!
> Division is fun!
```

---
### I'm Just Creating Problems Now

If `x=10` and `y=0` then:
```
try:
  print(x/y)
except ZeroDivisionError:
  print("You can't divide by zero!")
  raise Exception("Please don't do that again!")
finally: 
  print("Division is fun!")
```
Produces:
```
You can't divide by zero!
Division is fun!
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
ZeroDivisionError: division by zero

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
Exception: Please don't do that again!
```

---
